### PR TITLE
Support passing directories as command-line arguments

### PR DESCRIPTION
**Pull request by pgjones**
This makes it easier to run djhtml over a bunch of files in a
directory or directories.

The default suffixes are used as a filter with no configuration
allowed (as black seems to work).

I'm aware of #13 recommending using `find ... | xargs` or the usage of pre-commit. However, I would like a single command that works on Linux, MacOS, and crucially Windows systems (`find` and `xargs` don't work). This would allow me to recommend to users how to use djhtml without having to add lots of additional text explaining how to do it on different systems i.e. `djhtml src/templates` is all that is needed.

### CODE REVIEW

**Comment by pgjones** [comment]
@JaapJoris anything I can do to help this along?

**Review by JaapJoris — CHANGES_REQUESTED** [review]
Thank you very much for this valuable contribution! I especially like the clean and dependency-less implementation of `_generate_files()`.

However, there is one use case that seems to break with this change, and that is indenting files that end with non-obvious (or absent) extensions. A good example are the files inside the `tests/suite`.

Before:

```
$ djhtml -ic tests/suite/html.in
1 template would have been reindented.
```

After

```
$ djhtml -ic tests/suite/html.in
0 templates would have been reindented.
```

Preserving this behavior is important to guarantee that DjHTML will always act upon the arguments it receives, no matter their extension. It's especially important for the folks that are using the `files` argument to `pre-commit`, a recent example being #65 

If you are able to find an elegant solution to preserve the original behavior, while also adding in support for directory traversal, I will approve, merge, and release the PR. Good luck!

**Comment by pgjones** [comment]
That makes sense, I've updated and I believe it meets this requirement now.

**Review by JaapJoris — APPROVED** [review]

**Comment by pgjones** [comment]
Thanks :)

**Pull request merged**
